# Generated by Django 3.2.20 on 2023-08-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='s_address',
            field=models.CharField(max_length=255),
        ),
    ]
