# Generated by Django 3.2.20 on 2023-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_alter_studentmodel_s_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='t_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
