# Generated by Django 3.2.20 on 2023-09-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0004_auto_20230901_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='t_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
