# Generated by Django 3.2.20 on 2023-09-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0005_alter_teachermodel_t_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='t_email',
        ),
    ]
