# Generated by Django 3.2.20 on 2023-09-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0006_remove_teachermodel_t_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='t_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
